---
title: "Figure 7"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

# adventitious roots, organic layer and exposed mineral soil

```{r setting up}
  library(ggplot2)
  library(cowplot)
  library(dplyr)
  theme_set(theme_cowplot())
  rm(list = ls())
```

# adventitous roots

```{r adventitous roots plot}
adven_root <- read.csv("data/adventaguous_roots.csv")
adven_root_plot <- ggplot(adven_root, 
                          aes(x = factor(adven_root$TREAT),
                              y = adven_root$DEPTH, 
                              fill = adven_root$SITE)) + 
  geom_boxplot() + 
  labs(x = "Number of Fires", y = "Depth (cm)",
       title = "Soil Consumption") + 
  scale_fill_manual(values = c("#d9d9d9", "#ffffff"), name = "Site Type", labels = c("Upland", "Lowland")) + 
  theme(plot.title = element_text(hjust = 0),
        legend.position = "none") + xlim("1", "2")
adven_root_plot
# save_plot("adven_root.png", adven_root_plot, base_aspect_ratio = 1.5)
```

# organic layer depth

```{r organic layer plot}
org_depth <- read.csv("data/org_depth.csv")
 org_depth_plot <- ggplot(org_depth, 
                          aes(x = factor(org_depth$TREATMENT), y =
                                org_depth$ORG_DEPTH, 
                              fill = org_depth$SITE)) + 
    geom_boxplot()   + 
    scale_fill_manual(name = "Site Type",
                      values = c("#d9d9d9", "#ffffff"), 
                      labels = c("Upland", "Lowland")) + 
    labs(title = "Organic Layer Depth", 
         x = "Number of Fires", y = "Organic layer depth (cm)") + 
    theme(plot.title = element_text(hjust = 0), legend.position =  "none") 
org_depth_plot
  
# save_plot("org_depth.png", org_depth_plot, base_aspect_ratio = 1.5)
```

# Exposed mineral soil

```{r exposed mineral soil}
exposed_min <- read.csv("data/exposed_min.csv")
expose_min_plot <- ggplot(exposed_min, 
                          aes(x = factor(exposed_min$TREATMENT),
                              y = exposed_min$MINERAL,
                              fill = exposed_min$SITE)) + 
    geom_boxplot() + 
    scale_fill_manual(name = "Site Type",
                      values = c("#d9d9d9", "#ffffff"), 
                      labels = c("Upland", "Lowland")) + 
    labs(title = "Exposed Mineral Soil", 
         x = "Number of Fires", y = "% of Mineral Soil Exposed") + 
    theme(plot.title = element_text(hjust = 0))
expose_min_plot
```

# combining all three
```{r combined }
plot_grid(adven_root_plot, org_depth_plot, expose_min_plot,
          nrow = 1, ncol = 3,
          rel_widths = c(0.9, 0.9,1.3), rel_heights = c(1,1, 1.5),
          labels = c("A.", "B.", "C."))

save_plot("substrate.png", substrate, nrow = 1, ncol = 2, base_aspect_ratio = 1.5)

```

# getting numbers
## adven root
```{r getting mins and maxs uplands}
upland <- adven_root[adven_root$SITE == "DALTON",]

summary(upland$DEPTH[upland$TREAT == 1])

summary(upland$DEPTH[upland$TREAT == 2])
24/10
```

```{r getting mins and maxs lowland}
lowland <- adven_root[adven_root$SITE == "STEESE",]

summary(lowland$DEPTH[lowland$TREAT == 1])
low1 <- lowland$DEPTH[lowland$TREAT == 1]
low2 <- lowland$DEPTH[lowland$TREAT == 2]
t.test(low1,low2)
```

```{r anova / kruskal}
library(tidyverse)
library(ggpubr)
library(rstatix)

adven_root %>%
  group_by(SITE) %>%
  shapiro_test(DEPTH)

adven_root_stee <- adven_root[adven_root$SITE == "STEESE",]
adven_root_stee %>%
       dunn_test(DEPTH ~ TREAT, p.adjust.method = "bonferroni")
```

## organic layer

```{r getting maximums and minimums}
org_depth %>%
  filter(TREATMENT == 0) %>%
  summarise(mean(ORG_DEPTH))

```

